import type { Metadata } from 'next';
// import { Geist, Geist_Mono } from "next/font/google";
import './globals.css';
import { cookies } from 'next/headers';
import { AuthProvider } from '@/feature/auth/AuthContext';
import { LoginModalProvider } from '@/feature/auth/LoginAlertModalContext';
import GlobalLoginAlertModal from '@/feature/auth/modal/GlobalLoginAlertModal';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: '네이버 마켓',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const hasToken = cookieStore.has('accessToken');

  return (
    <html lang="ko">
      <body className="font-sans text-[#222222]">
        <AuthProvider initialIsLoggedIn={hasToken}>
          <LoginModalProvider>
            {children}
            <GlobalLoginAlertModal />
          </LoginModalProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
