import type { Metadata } from 'next';
// import { Geist, Geist_Mono } from "next/font/google";
import './globals.css';
import { cookies } from 'next/headers';
import { AuthProvider } from '@/feature/auth/AuthContext';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const hasToken = cookieStore.has('accessToken');

  return (
    <html lang="ko">
      <body className="font-sans text-[#222222]">
        <AuthProvider initialIsLoggedIn={hasToken}>{children}</AuthProvider>
      </body>
    </html>
  );
}
