### 회원 가입 API 테스트
# POST http://localhost:8080/api/users/signUp
# Content-Type: application/json

# {

#   "email": "asd2@naver.com",
#   "pwd": "123",
#   "name": "Tester2",
#   "loginId": "TesterID2",
#   "phone": "010-0000-0000",
#   "address": "Seoul",
#   "detailAddress": "2호",
#   "isTermsAgreed": true,
#   "isPrivacyAgreed": true,
#   "isMarketingAgreed": false

# }

### 1. 로그인 API 테스트 (여기 ### 3개가 필수입니다!)
POST http://localhost:8080/api/users/signIn
Content-Type: application/json

{
  "loginId": "TesterID2",
  "pwd": "123"
}

### 2. [실패 케이스] 토큰 없이 보안 구역 접근 시도
GET http://localhost:8080/api/users/me


### 3. [성공 케이스] 정당한 토큰으로 보안 구역 접근
# 주의: 반드시 'Bearer ' (띄어쓰기 포함) 뒤에 토큰을 넣어야 합니다!
GET http://localhost:8080/api/users/me
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJUZXN0ZXJJRDIiLCJpYXQiOjE3NzIxODQxMjUsImV4cCI6MTc3MjE4NzcyNX0.2eEynx9KyloWZURA_WHGGas9fXu4u9_KONknHp3TsOF5DE1k_8iZE1G9sylT9pRIJecYIVjS99oP44ZJxm0HBweyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJUZXN0ZXJJRDIiLCJpYXQiOjE3NzIxODQxNDEsImV4cCI6MTc3MjE4Nzc0MX0.ctTUEmtXrQCoZNAn_XpMULDqKNQA8jzPdnf-0r02volDOQh187DLdoezRnEfM_eduCPeFNOsW2YNcAqW2elCfQ